# Build a Java project, with Gradle
# see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI, gradle

on:
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8 environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build using Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: build/libs 
        # This currently fails - the build doesn't output anything to this directory
