name: Generate JavaDocs and push to website

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/**'
    branches: [ master ]

jobs:
  javadocs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8 environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate JavaDocs using Gradle
      run: |
          ./gradlew javadoc
    
    - name: Push to website docs/ folder
      run: |
          rm -rf docs/javadocs
          mv core/build/docs/javadoc docs/javadocs
          
          git add -all
          
          git config --local user.email "action@github.com"
          git config --local user.name "Update JavaDocs"
          
          git commit -m "Push updated javadocs"
          git push
    


 
