# Build a Java project, with Gradle
# see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI and deployment

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/**'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/**'
    branches: [ master ]

jobs:
  test: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8 environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test using Gradle
      run: ./gradlew test
    
   
  build_and_deploy:
    needs: test # this makes it so build + deploy will be skipped if test fails
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8 environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build using Gradle
      run: ./gradlew desktop:dist
      
    - name: Create a new release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      
    - name: Upload .jar file to release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: desktop/build/libs/game.jar
        asset_content_type: application/java-archive
        asset_name: game.jar
        
    - name: Update .jar in repo linked to on website
      run: |
          mv desktop/build/libs/game.jar ./
          git add game.jar
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          
          git commit -m "Update .jar file" -a
          git push
